 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shortners", type: :request do
  # Shortner. As you add validations to Shortner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Shortner.create! valid_attributes
      get shortners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shortner = Shortner.create! valid_attributes
      get shortner_url(shortner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_shortner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      shortner = Shortner.create! valid_attributes
      get edit_shortner_url(shortner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Shortner" do
        expect {
          post shortners_url, params: { shortner: valid_attributes }
        }.to change(Shortner, :count).by(1)
      end

      it "redirects to the created shortner" do
        post shortners_url, params: { shortner: valid_attributes }
        expect(response).to redirect_to(shortner_url(Shortner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Shortner" do
        expect {
          post shortners_url, params: { shortner: invalid_attributes }
        }.to change(Shortner, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post shortners_url, params: { shortner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shortner" do
        shortner = Shortner.create! valid_attributes
        patch shortner_url(shortner), params: { shortner: new_attributes }
        shortner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the shortner" do
        shortner = Shortner.create! valid_attributes
        patch shortner_url(shortner), params: { shortner: new_attributes }
        shortner.reload
        expect(response).to redirect_to(shortner_url(shortner))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shortner = Shortner.create! valid_attributes
        patch shortner_url(shortner), params: { shortner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shortner" do
      shortner = Shortner.create! valid_attributes
      expect {
        delete shortner_url(shortner)
      }.to change(Shortner, :count).by(-1)
    end

    it "redirects to the shortners list" do
      shortner = Shortner.create! valid_attributes
      delete shortner_url(shortner)
      expect(response).to redirect_to(shortners_url)
    end
  end
end
